# Inleiding Python

## Algemeen
### Python als rekenmachine

In [2]:
# dit is commentaar

"""
dit is commentaar
over verschillende regels heen
maar het is een beetje een 'hack'
dit is namelijk een string literal
die over verschillende regels heen gaat
"""

# je kan ook iedere
# lijn apart in commentaar zetten
# dat is veel mooier :-)

print(6 * 7) # eenvoudige vermenigvuldiging
print(2 ** 3) # machtsverheffing
print((2+4)*(9-2)) # haakjes
3*4 # zonder print(): enkel laatste commando

42
8
42


12

In [4]:
import math # Je kan een bibliotheek importeren.  PyCharm zal voorstellen om de bib te installeren
print(59.396969619669996 * math.sin(math.pi/4)) # goniometrische functies (Python werkt met radialen)

42.00000000000001


### Variabelen en types

In [5]:
# geen declaratie nodig
# het type wordt automatisch bepaald
# het type mag veranderen
a = 3 * 14
print(a)
print(a * 7 + 3)
print('type van a = ', type(a))

42
297
type van a =  <class 'int'>


In [6]:
a = "bla"
print('a = ', a)
print('type van a = ', type(a))

a =  bla
type van a =  <class 'str'>


In [7]:
# er is geen char-type
a = 'bla'
print('a = ', a)
print('type van a = ', type(a))

a =  bla
type van a =  <class 'str'>


In [8]:
a = 42.5
print('a = ', a)
print('type van a = ', type(a))
a = int(a) # casting gebeurt met functies int(), float(), str(), ...
print(a)

a =  42.5
type van a =  <class 'float'>
42


In [9]:
a = True
print('a = ', a)
print('type van a = ', type(a))

a =  True
type van a =  <class 'bool'>


In [11]:
# variabelnamen: gebruik underscore ipv camelCase
mijn_variabele = 5
print(mijn_variabele)

5


In [10]:
mijn_variabele = 127 / 3
print(mijn_variabele) # float!

42.333333333333336


In [12]:
mijn_variabele = 127 // 3
print(mijn_variabele)

42


### IEEE 754

In [13]:
a = math.inf
print('a = ', a)
b = math.nan
print('b = ', b)

a =  inf
b =  nan


In [ ]:
# verklaar het resultaat...
d = 2927.6 + 67 + 63 + 63 + 70 - 3142.5
print('d = ', d)

## Lijsten
Er zijn 3 soorten lijsten:
* Python lists
* Numpy arrays
* Pandas Series

### Python lists

In [17]:
x = [ 3, 4, 5, 6, 7, 8, 9, 10 ]
print(x)

[3, 4, 5, 6, 7, 8, 9, 10]


In [16]:
print(len(x)) # niet met een methode...

4


In [15]:
x = list(range(3,11,2)) # je kan een lijst maken van een range
print(x)

[3, 5, 7, 9]


In [18]:
y = x + [ 11, 12, 13 ]
print(y)

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]


In [19]:
x = [ 1, 2, 3 ]
print(x * 3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [20]:
x = [ 42, 3.14, 'hallo', True ] # verschillende types
print(x)

[42, 3.14, 'hallo', True]


In [21]:
print(x)
print(x[2])

[42, 3.14, 'hallo', True]
hallo


In [22]:
print(x)
print(x[-1]) # index<0 => lengte-index

[42, 3.14, 'hallo', True]
True


In [23]:
print(x)
print(x[1:4]) # slicing

[42, 3.14, 'hallo', True]
[3.14, 'hallo', True]


In [ ]:
print(x)
print(x[1:4:2])

komt overeen met (Java):
for(int i=1; i<4; i+=2)

In [24]:
print(x)
print(x[::2])

[42, 3.14, 'hallo', True]
[42, 'hallo']


In [25]:
print(x)
print(x[::-1])

[42, 3.14, 'hallo', True]
[True, 'hallo', 3.14, 42]


### Pandas Series

In [28]:
import pandas as pd

In [29]:
# Series maken
# Series is eigenlijk een map
lijst = [10, 20, 30, 40, 50, 60]
series = pd.Series(lijst)
print(series)
print("lengte = ", len(series))

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64
lengte =  6


In [30]:
# terug omzetten naar list
print(series.to_list())

[10, 20, 30, 40, 50, 60]


In [31]:
# rekenen met Series
series = pd.Series([2, 2, 0, 5, 1, 4, 4, 0, 0, 3])

In [32]:
print((series * 3).to_list())

[6, 6, 0, 15, 3, 12, 12, 0, 0, 9]


In [33]:
print((series + 10).to_list())

[12, 12, 10, 15, 11, 14, 14, 10, 10, 13]


In [39]:
series2 = pd.Series([1, 4, 4, 3, 4, 0, 0, 3, 4, 1])

In [35]:
print((series + series2).to_list())

[3, 6, 4, 8, 5, 4, 4, 3, 4, 4]


In [36]:
print((series * series2).to_list())

[2, 8, 0, 15, 4, 0, 0, 0, 0, 3]


In [37]:
series3 = pd.Series(range(1,5))
print((series + series3))

0    3.0
1    4.0
2    3.0
3    9.0
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
dtype: float64


In [38]:
# selecties
series = pd.Series(range(1,10))
print(series)
print(series[2:9:2])

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
2    3
4    5
6    7
8    9
dtype: int64


In [40]:
select = [0, 2, 1] # gewone list
print(series[select]) # geen for nodig

0    1
2    3
1    2
dtype: int64


In [41]:
print(series)
print(series > 4)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
0    False
1    False
2    False
3    False
4     True
5     True
6     True
7     True
8     True
dtype: bool


In [42]:
print(series[series > 4])

4    5
5    6
6    7
7    8
8    9
dtype: int64


In [43]:
even = ((series % 2) == 0)
#print(even)
print(series[even])

1    2
3    4
5    6
7    8
dtype: int64


In [44]:
vakken = pd.Series(['data science', 'programmeren', 'databanken', 'hardware', 'operating systems'])
scores = pd.Series([18, 15, 13, 16, 12])

In [45]:
print(vakken[scores > 15])

0    data science
3        hardware
dtype: object


In [46]:
# Series als een map
series = pd.Series([10, 20, 30, 40, 50], index=[4, 3, 8, 6, 10])
print(series)

4     10
3     20
8     30
6     40
10    50
dtype: int64


In [47]:
series[100] = 5
series['hello'] = 42
print(series)

4        10
3        20
8        30
6        40
10       50
100       5
hello    42
dtype: int64


In [48]:
series['hello']

42

In [49]:
series[99]

KeyError: 99

### Numpy arrays

In [50]:
import numpy as np

In [51]:
arr = np.zeros(10, dtype=int)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


In [52]:
arr = np.ones(5, dtype=float)
print(arr)

[1. 1. 1. 1. 1.]


In [53]:
arr = np.random.randint(6, size=10)+1
print(arr)

[6 2 3 3 6 5 4 2 3 5]


In [54]:
list(range(1.1,10,3))

TypeError: 'float' object cannot be interpreted as an integer

In [55]:
arr = np.arange(1.1, 2, 0.3)
print(arr)

[1.1 1.4 1.7]


In [56]:
lijst = [ 1, 2, 3 ]
arr = np.array(lijst)
print(arr)

[1 2 3]


In [57]:
print(type(arr))

<class 'numpy.ndarray'>


In [58]:
arr = np.random.randint(6, size=10)
lijst = arr.tolist()
print(lijst)
print(type(lijst))

[0, 5, 2, 5, 3, 4, 3, 3, 2, 2]
<class 'list'>


## Kwalitatieve gegevens

In [59]:
# hoeveel geheugen gebruikt volgende list?
mening = [ 'niet belangrijk', 'heel belangrijk', 'heel belangrijk', 'een beetje belangrijk', 'heel belangrijk', 'een beetje belangrijk', 'een beetje belangrijk', 'niet belangrijk', 'heel belangrijk', 'heel belangrijk']

In [60]:
# omzetten naar categorical
meningMogelijkheden = [ 'niet belangrijk', 'een beetje belangrijk', 'heel belangrijk', 'extreem belangrijk' ]
meningIndexen = [ 0, 2, 2, 1, 2, 1, 1, 0, 2, 2 ]

In [61]:
meningSeries = pd.Categorical(mening, categories=meningMogelijkheden)
print(meningSeries)

['niet belangrijk', 'heel belangrijk', 'heel belangrijk', 'een beetje belangrijk', 'heel belangrijk', 'een beetje belangrijk', 'een beetje belangrijk', 'niet belangrijk', 'heel belangrijk', 'heel belangrijk']
Categories (4, object): ['niet belangrijk', 'een beetje belangrijk', 'heel belangrijk', 'extreem belangrijk']


In [62]:
# je kan de getallen en categorieën apart terug uit het object halen
print(meningSeries.codes)

[0 2 2 1 2 1 1 0 2 2]


In [63]:
print(meningSeries.categories.tolist())

['niet belangrijk', 'een beetje belangrijk', 'heel belangrijk', 'extreem belangrijk']


In [64]:
meningSeries = pd.Categorical(mening, categories=meningMogelijkheden, ordered=True)
print(meningSeries)
print(meningSeries.categories.tolist())
print(meningSeries.codes)

['niet belangrijk', 'heel belangrijk', 'heel belangrijk', 'een beetje belangrijk', 'heel belangrijk', 'een beetje belangrijk', 'een beetje belangrijk', 'niet belangrijk', 'heel belangrijk', 'heel belangrijk']
Categories (4, object): ['niet belangrijk' < 'een beetje belangrijk' < 'heel belangrijk' < 'extreem belangrijk']
['niet belangrijk', 'een beetje belangrijk', 'heel belangrijk', 'extreem belangrijk']
[0 2 2 1 2 1 1 0 2 2]


## Data frames

### Aanmaken

In [65]:
x = pd.Series(range(1,6))
y = [ "foo", "bar", "bla", "boe", "foo" ]
z = np.random.randint(10, size=5)
f  = pd.DataFrame({'id': x, 'naam': y, 'score': z}) # we gebruiken hier een "dictionary"
print(f)

   id naam  score
0   1  foo      1
1   2  bar      5
2   3  bla      6
3   4  boe      7
4   5  foo      4


### Gebruiken en manipuleren

Veel gebruikte eigenschappen:

In [66]:
print(f)
print("aantal rijen: ", len(f))
print("aantal kolommen: ", f.columns.size)
print("kolomnamen: ", f.columns.tolist())
print("rijnamen: ", f.index.tolist())

   id naam  score
0   1  foo      1
1   2  bar      5
2   3  bla      6
3   4  boe      7
4   5  foo      4
aantal rijen:  5
aantal kolommen:  3
kolomnamen:  ['id', 'naam', 'score']
rijnamen:  [0, 1, 2, 3, 4]


Kolommen selecteren:

In [67]:
print(f['id'])

0    1
1    2
2    3
3    4
4    5
Name: id, dtype: int64


In [68]:
print(f["naam"])

0    foo
1    bar
2    bla
3    boe
4    foo
Name: naam, dtype: object


In [69]:
print(f.id)

0    1
1    2
2    3
3    4
4    5
Name: id, dtype: int64


In [70]:
print(f.naam)

0    foo
1    bar
2    bla
3    boe
4    foo
Name: naam, dtype: object


Kolommen verwijderen:

In [71]:
f.drop(columns="id")
print(f) # is de kolom weg?

   id naam  score
0   1  foo      1
1   2  bar      5
2   3  bla      6
3   4  boe      7
4   5  foo      4


In [72]:
f = f.drop(columns='id')

In [73]:
#f.drop(columns="id", inplace=True)
print(f)

  naam  score
0  foo      1
1  bar      5
2  bla      6
3  boe      7
4  foo      4


Kolommen toevoegen:

In [74]:
f["key"] = [ 10, 20, 30, 60, 40 ]
print(f)

  naam  score  key
0  foo      1   10
1  bar      5   20
2  bla      6   30
3  boe      7   60
4  foo      4   40


Rijen selecteren:

In [75]:
# gebruik .loc om een rij te selecteren
print(f.loc[1]) # geeft een Series

naam     bar
score      5
key       20
Name: 1, dtype: object


In [76]:
# meerdere rijen selecteren levert een data frame
print(f.loc[1:3]) # laatste index inclusief!!!

  naam  score  key
1  bar      5   20
2  bla      6   30
3  boe      7   60


In [77]:
f = f.drop(1) # verwijder de rij met nummer 1
print(f)

  naam  score  key
0  foo      1   10
2  bla      6   30
3  boe      7   60
4  foo      4   40


In [78]:
#f.drop(1) # error: er is geen rij nummer 1 meer...

Data frame als een 2-dimensionale array:

In [79]:
# gebruik iloc voor rij- en kolomnummers
print(f)
print(f.iloc[3,2])

  naam  score  key
0  foo      1   10
2  bla      6   30
3  boe      7   60
4  foo      4   40
40


In [80]:
# selecteer een rijnummer
print(f.iloc[3])

naam     foo
score      4
key       40
Name: 4, dtype: object


In [81]:
# selecteer verschillende rijnummers
print(f.iloc[1:4])

  naam  score  key
2  bla      6   30
3  boe      7   60
4  foo      4   40


In [82]:
# wat doet dit?
print(f.iloc[-1])

naam     foo
score      4
key       40
Name: 4, dtype: object


In [83]:
# combinatie van rijen en kolommen
print(f.iloc[0:2,1:3])

   score  key
0      1   10
2      6   30


Informatie over data frame:

In [84]:
print(f.head(n=3))

  naam  score  key
0  foo      1   10
2  bla      6   30
3  boe      7   60


In [85]:
print(f.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   naam    4 non-null      object
 1   score   4 non-null      int32 
 2   key     4 non-null      int64 
dtypes: int32(1), int64(1), object(1)
memory usage: 112.0+ bytes
None


In [86]:
f.describe()

score       key
count  4.000000   4.00000
mean   4.500000  35.00000
std    2.645751  20.81666
min    1.000000  10.00000
25%    3.250000  25.00000
50%    5.000000  35.00000
75%    6.250000  45.00000
max    7.000000  60.00000

In [87]:
f.naam.describe()

count       4
unique      3
top       foo
freq        2
Name: naam, dtype: object

## Functies schrijven

In [88]:
# zie je wat volgende code doet?
# indentatie is belangrijk! (geen accolades)
def mijn_functie(n):
    result = np.sqrt(n)/2
    return result

In [89]:
print(mijn_functie(9))

1.5


Meerdere return-values:

In [90]:
def minmax(x):
  return [ np.min(x), np.max(x) ]

In [91]:
mi, ma = minmax([1,2,3,4,5])
print(mi)
print(ma)

1
5


Parameters:

In [92]:
def mijn_functie(a, b, c):
  return a + b - c

In [93]:
mijn_functie(10, 5, 1)

14

In [94]:
mijn_functie(b=5, a=10, c=1)

14

Default waarden:

In [95]:
def verhoog(getal, aantal=1):
  return getal + aantal

In [96]:
print(verhoog(41))
print(verhoog(40, 2))

42
42


## Controlestructuren

In [97]:
# zie je wat volgende code doet?
def zoek(element, lijst):
  if len(lijst)==0:
    return False
  else:
    for d in lijst: # for lus is altijd een foreach
      if d==element: # geen .equals()
        return True
    return False

In [98]:
print(zoek(4, [3,4,6,8]))
print(zoek(4, [3,6,8]))

True
False


In [99]:
# dit is hetzelfde, maar met een while lus
def zoek(element, lijst):
  if len(lijst)==0:
    return False
  else:
    i = 0
    while i < len(lijst):
      if lijst[i]==element:
        return True
      i = i + 1
    return False

In [100]:
print(zoek(4, [3,4,6,8]))
print(zoek(4, [3,6,8]))

True
False


## Functioneel programmeren

In [101]:
# kan je zien wat volgende code doet?
def pas_functie_toe(lijst, functie):
  resultaat = []
  for element in lijst:
    resultaat = resultaat + [ functie(element) ]
  return resultaat

In [102]:
def verhoog(n):
  return n + 1

In [103]:
# verklaar de output
lijst = [10, 20, 30]
result = pas_functie_toe(lijst, verhoog)
print(result)

[11, 21, 31]


In [104]:
# de types moeten nu wel kloppen...
a = 1
pas_functie_toe(a, verhoog)

In [105]:
# deze functionaliteit bestaat al in Series (apply)
lijst = pd.Series([10, 20, 30])
lijst2 = lijst.apply(verhoog)
print(lijst2)

0    11
1    21
2    31
dtype: int64


## Eigen bibliotheken maken

In [106]:
import os, sys
parent_dir = os.path.abspath('../..') # verwijst naar de basisfolder van dit project
if parent_dir not in sys.path:
    sys.path.append(parent_dir)

In [107]:
import lessen.week2_Python.script as script

script.repeat(3,5)

ModuleNotFoundError: No module named 'lessen'